import type { ItemDefinition, ItemId } from "../../game/types";

export const ITEMS: Record<ItemId, ItemDefinition> = {
  iron_ore: { id: "iron_ore", name: "铁矿石", symbol: "Fe", color: "#9aa6a8", kind: "solid", description: "铁系生产链的基础矿物。" },
  copper_ore: { id: "copper_ore", name: "铜矿石", symbol: "Cu", color: "#d2764c", kind: "solid", description: "电气元件所需的基础矿物。" },
  coal: { id: "coal", name: "煤矿", symbol: "C", color: "#6e7471", kind: "solid", description: "燃料和高能石墨的基础资源。" },
  stone: { id: "stone", name: "石矿", symbol: "St", color: "#b5a68d", kind: "solid", description: "建筑材料与玻璃的基础原料。" },
  crude_oil: { id: "crude_oil", name: "原油", symbol: "Oil", color: "#735d46", kind: "fluid", description: "从原油涌泉持续萃取的化工原料。" },
  silicon_ore: { id: "silicon_ore", name: "硅石", symbol: "SiO", color: "#78948c", kind: "solid", description: "远端矿区出产的半导体基础矿物。" },
  titanium_ore: { id: "titanium_ore", name: "钛石", symbol: "TiO", color: "#80769c", kind: "solid", description: "远端矿区出产的高强度金属矿物。" },
  fire_ice: { id: "fire_ice", name: "可燃冰", symbol: "FI", color: "#87b9c5", kind: "solid", description: "气态巨星轨道中的稀有冰晶，可直接裂解为石墨烯和氢。" },
  kimberlite_ore: { id: "kimberlite_ore", name: "金伯利矿石", symbol: "Kim", color: "#8aa29c", kind: "solid", description: "富含天然金刚石结构的稀有矿物。" },
  fractal_silicon: { id: "fractal_silicon", name: "分形硅石", symbol: "FrSi", color: "#82aaa4", kind: "solid", description: "具有规则分形晶格的稀有硅矿，可高效加工晶格硅。" },
  optical_grating_crystal: { id: "optical_grating_crystal", name: "光栅石", symbol: "OGC", color: "#d4b866", kind: "solid", description: "天然形成的精密光栅晶体，可旁路高级光学和卡西米尔配方。" },
  spiniform_stalagmite_crystal: { id: "spiniform_stalagmite_crystal", name: "刺笋结晶", symbol: "SSC", color: "#829c9d", kind: "solid", description: "拥有天然纳米管结构的稀有晶体，可直接制造碳纳米管。" },
  unipolar_magnet: { id: "unipolar_magnet", name: "单极磁石", symbol: "UM", color: "#7c91b0", kind: "solid", description: "极端磁场环境形成的单极材料，可大幅简化粒子容器生产。" },
  water: { id: "water", name: "水", symbol: "H2O", color: "#529fc1", kind: "fluid", description: "由抽水站从海洋水源持续取得的化工原料。" },
  sulfuric_acid: { id: "sulfuric_acid", name: "硫酸", symbol: "H2S", color: "#b7b957", kind: "fluid", description: "可由化工厂合成，也可从熔岩星硫酸海洋直接抽取。" },
  iron_ingot: { id: "iron_ingot", name: "铁块", symbol: "I", color: "#c1cbcc", kind: "solid", description: "最常用的基础结构材料。" },
  copper_ingot: { id: "copper_ingot", name: "铜块", symbol: "C", color: "#e18b5d", kind: "solid", description: "导电元件的基础材料。" },
  magnet: { id: "magnet", name: "磁铁", symbol: "M", color: "#718da4", kind: "solid", description: "磁场设备的基础零件。" },
  stone_brick: { id: "stone_brick", name: "石材", symbol: "Br", color: "#c5bba9", kind: "solid", description: "耐热建筑结构材料。" },
  glass: { id: "glass", name: "玻璃", symbol: "Gl", color: "#8fc7c6", kind: "solid", description: "科研和光学设备所需材料。" },
  steel: { id: "steel", name: "钢材", symbol: "Stl", color: "#7f9298", kind: "solid", description: "重型工业设备所需的高强度结构材料。" },
  gear: { id: "gear", name: "齿轮", symbol: "G", color: "#d2aa5b", kind: "solid", description: "机械传动结构的通用零件。" },
  magnetic_coil: { id: "magnetic_coil", name: "磁线圈", symbol: "Mc", color: "#dd6d5b", kind: "solid", description: "由磁铁与铜块绕制而成。" },
  circuit_board: { id: "circuit_board", name: "电路板", symbol: "Cb", color: "#78b776", kind: "solid", description: "自动化设备的基础控制元件。" },
  prism: { id: "prism", name: "棱镜", symbol: "Pr", color: "#8ecbc3", kind: "solid", description: "由玻璃加工成的光学元件。" },
  plasma_exciter: { id: "plasma_exciter", name: "电浆激发器", symbol: "Px", color: "#d78961", kind: "solid", description: "原油萃取和精炼设备的关键部件。" },
  energetic_graphite: { id: "energetic_graphite", name: "高能石墨", symbol: "EG", color: "#817b8f", kind: "solid", description: "能源矩阵所需的高密度碳材料。" },
  refined_oil: { id: "refined_oil", name: "精炼油", symbol: "RO", color: "#c99a4b", kind: "fluid", description: "原油精炼的主要液体产物。" },
  hydrogen: { id: "hydrogen", name: "氢", symbol: "H", color: "#9dd5d3", kind: "fluid", description: "能源矩阵和后续化工链的重要气体资源。" },
  high_purity_silicon: { id: "high_purity_silicon", name: "高纯硅块", symbol: "Si", color: "#73aaa1", kind: "solid", description: "处理器与精密电子元件的基础半导体材料。" },
  titanium_ingot: { id: "titanium_ingot", name: "钛块", symbol: "Ti", color: "#978db4", kind: "solid", description: "结构矩阵产业链所需的高强度金属材料。" },
  titanium_alloy: { id: "titanium_alloy", name: "钛合金", symbol: "TiA", color: "#9d9cb9", kind: "solid", description: "钛、钢材与硫酸共同形成的耐高温星际结构材料。" },
  microcrystalline_component: { id: "microcrystalline_component", name: "微晶元件", symbol: "McC", color: "#67a994", kind: "solid", description: "以高纯硅块制造的精密半导体元件。" },
  processor: { id: "processor", name: "处理器", symbol: "CPU", color: "#60a985", kind: "solid", description: "星际物流与高级自动化设备的核心控制单元。" },
  logistics_drone: { id: "logistics_drone", name: "物流运输机", symbol: "LD", color: "#70aeb0", kind: "solid", description: "装载到行星物流站后执行同一行星内的无线运输，每架运载 25 件货物。" },
  logistics_vessel: { id: "logistics_vessel", name: "物流运输船", symbol: "LV", color: "#d4865d", kind: "solid", description: "装载到星际物流站后执行跨行星运输，每艘运载 100 件货物。" },
  space_warper: { id: "space_warper", name: "空间翘曲器", symbol: "Wrp", color: "#8c79c7", kind: "solid", description: "供物流运输船跨恒星航行时消耗的曲率驱动介质。" },
  accumulator: { id: "accumulator", name: "蓄电器", symbol: "Acc", color: "#789993", kind: "solid", description: "可由能量枢纽充电并跨行星运输的空储能单元。" },
  charged_accumulator: { id: "charged_accumulator", name: "蓄电器（满）", symbol: "Acc+", color: "#8fc8a3", kind: "solid", description: "储有 90 MJ 电能，可在能量枢纽放电后还原为空蓄电器。" },
  graphene: { id: "graphene", name: "石墨烯", symbol: "Gr", color: "#749692", kind: "solid", description: "由高能石墨剥离形成的二维碳材料。" },
  carbon_nanotube: { id: "carbon_nanotube", name: "碳纳米管", symbol: "CNT", color: "#7e969d", kind: "solid", description: "石墨烯与钛材料形成的高强度纳米结构。" },
  proliferator_mk1: { id: "proliferator_mk1", name: "增产剂 Mk.I", symbol: "P1", color: "#8f9872", kind: "solid", description: "由煤加工的基础喷涂介质，每件提供 12 个喷涂点数。" },
  proliferator_mk2: { id: "proliferator_mk2", name: "增产剂 Mk.II", symbol: "P2", color: "#56a58f", kind: "solid", description: "加入金刚石强化的增产剂，每件提供 24 个喷涂点数。" },
  proliferator_mk3: { id: "proliferator_mk3", name: "增产剂 Mk.III", symbol: "P3", color: "#628fba", kind: "solid", description: "利用碳纳米管稳定喷涂结构，每件提供 60 个喷涂点数。" },
  crystal_silicon: { id: "crystal_silicon", name: "晶格硅", symbol: "CSi", color: "#84b5a5", kind: "solid", description: "由高纯硅块进一步重排得到的精密晶格材料。" },
  particle_broadband: { id: "particle_broadband", name: "粒子宽带", symbol: "PB", color: "#b486b1", kind: "solid", description: "由纳米碳、晶格硅与塑料制造的信息载体。" },
  electric_motor: { id: "electric_motor", name: "电动机", symbol: "Mot", color: "#547e91", kind: "solid", description: "由铁、齿轮与磁线圈制造的基础动力组件。" },
  electromagnetic_turbine: { id: "electromagnetic_turbine", name: "电磁涡轮", symbol: "Tur", color: "#4f9b9e", kind: "solid", description: "高速电磁设备与粒子容器所需的动力核心。" },
  super_magnetic_ring: { id: "super_magnetic_ring", name: "超级磁场环", symbol: "SMR", color: "#3fa6a0", kind: "solid", description: "约束高能粒子和制造氘核燃料棒的强磁组件。" },
  particle_container: { id: "particle_container", name: "粒子容器", symbol: "PC", color: "#71a9aa", kind: "solid", description: "利用电磁涡轮与石墨烯约束高能粒子的容器。" },
  deuterium: { id: "deuterium", name: "氘", symbol: "D", color: "#86c7d0", kind: "fluid", description: "由氢在粒子对撞过程中富集得到的高能同位素。" },
  hydrogen_fuel_rod: { id: "hydrogen_fuel_rod", name: "氢燃料棒", symbol: "HFR", color: "#7ab4c0", kind: "solid", description: "将氢封装为便于运输和火力发电的中密度燃料。" },
  deuteron_fuel_rod: { id: "deuteron_fuel_rod", name: "氘核燃料棒", symbol: "DFR", color: "#67b8c0", kind: "solid", description: "以氘和超级磁场环封装的高密度燃料。" },
  titanium_glass: { id: "titanium_glass", name: "钛化玻璃", symbol: "TiG", color: "#8fc6c1", kind: "solid", description: "兼具高透明度与结构强度的精密材料。" },
  casimir_crystal: { id: "casimir_crystal", name: "卡西米尔晶体", symbol: "Cas", color: "#74b9a4", kind: "solid", description: "利用氢与纳米材料形成的量子级晶体。" },
  plane_filter: { id: "plane_filter", name: "位面过滤器", symbol: "PF", color: "#75a2bd", kind: "solid", description: "由卡西米尔晶体与钛化玻璃组成的精密过滤结构。" },
  quantum_chip: { id: "quantum_chip", name: "量子芯片", symbol: "QC", color: "#6d8ec0", kind: "solid", description: "引力矩阵所需的高性能量子运算核心。" },
  strange_matter: { id: "strange_matter", name: "奇异物质", symbol: "SM", color: "#ae86bf", kind: "solid", description: "由粒子对撞机在极端能级下制造的非常规物质。" },
  graviton_lens: { id: "graviton_lens", name: "引力透镜", symbol: "GL", color: "#8fb676", kind: "solid", description: "利用奇异物质改变局部引力场的精密器件。" },
  photon_combiner: { id: "photon_combiner", name: "光子合并器", symbol: "PhC", color: "#d8b65f", kind: "solid", description: "汇聚光能并稳定太阳帆工作面的光学部件。" },
  solar_sail: { id: "solar_sail", name: "太阳帆", symbol: "Sail", color: "#e4c55f", kind: "solid", description: "由电磁轨道弹射器发射到恒星轨道，为戴森云提供能量。" },
  critical_photon: { id: "critical_photon", name: "临界光子", symbol: "CP", color: "#d8e2d7", kind: "solid", description: "射线接收站在光子模式下凝聚的高能光子。" },
  antimatter: { id: "antimatter", name: "反物质", symbol: "AM", color: "#d3c4e5", kind: "fluid", description: "由临界光子进行质能转换得到的高能物质。" },
  annihilation_constraint_sphere: { id: "annihilation_constraint_sphere", name: "湮灭约束球", symbol: "ACS", color: "#93a5b8", kind: "solid", description: "约束反物质湮灭反应的精密容器。" },
  antimatter_fuel_rod: { id: "antimatter_fuel_rod", name: "反物质燃料棒", symbol: "AFR", color: "#c9bde1", kind: "solid", description: "封装反物质与氢的终极高密度燃料。" },
  frame_material: { id: "frame_material", name: "框架材料", symbol: "Frm", color: "#7faeb0", kind: "solid", description: "由碳纳米管、钛合金和高纯硅构成的戴森球高强度骨架材料。" },
  dyson_sphere_component: { id: "dyson_sphere_component", name: "戴森球组件", symbol: "DSC", color: "#81b79f", kind: "solid", description: "封装框架、太阳帆和处理器的戴森球结构组件。" },
  small_carrier_rocket: { id: "small_carrier_rocket", name: "小型运载火箭", symbol: "Rkt", color: "#d18a58", kind: "solid", description: "由垂直发射井送入恒星轨道，用于建设戴森球永久结构。" },
  diamond: { id: "diamond", name: "金刚石", symbol: "Dia", color: "#a8d5ce", kind: "solid", description: "由高能石墨重排形成的高强度晶体。" },
  plastic: { id: "plastic", name: "塑料", symbol: "Pl", color: "#d1c3a3", kind: "solid", description: "精炼油与高能石墨合成的高分子材料。" },
  organic_crystal: { id: "organic_crystal", name: "有机晶体", symbol: "Org", color: "#74ad69", kind: "solid", description: "由塑料、精炼油和水合成的有机材料。" },
  titanium_crystal: { id: "titanium_crystal", name: "钛晶石", symbol: "TiC", color: "#b19ac8", kind: "solid", description: "钛块与有机晶体形成的结构矩阵中间体。" },
  electromagnetic_matrix: { id: "electromagnetic_matrix", name: "电磁矩阵", symbol: "EM", color: "#56b8cf", kind: "matrix", description: "第一阶段科研矩阵。" },
  energy_matrix: { id: "energy_matrix", name: "能量矩阵", symbol: "En", color: "#d85f50", kind: "matrix", description: "由氢与高能石墨制成的第二阶段科研矩阵。" },
  structure_matrix: { id: "structure_matrix", name: "结构矩阵", symbol: "Str", color: "#dfba48", kind: "matrix", description: "由金刚石与钛晶石制成的第三阶段科研矩阵。" },
  information_matrix: { id: "information_matrix", name: "信息矩阵", symbol: "Inf", color: "#9b77cf", kind: "matrix", description: "由粒子宽带与处理器制成的第四阶段科研矩阵。" },
  gravity_matrix: { id: "gravity_matrix", name: "引力矩阵", symbol: "Grv", color: "#77bd76", kind: "matrix", description: "由引力透镜与量子芯片制成的第五阶段科研矩阵。" },
  universe_matrix: { id: "universe_matrix", name: "宇宙矩阵", symbol: "Uni", color: "#d9dedb", kind: "matrix", description: "五色矩阵与反物质融合形成的最终阶段科研矩阵。" },
};

export const MATRIX_ITEM_IDS: ItemId[] = [
  "electromagnetic_matrix",
  "energy_matrix",
  "structure_matrix",
  "information_matrix",
  "gravity_matrix",
  "universe_matrix",
];

