import type { PlanetDefinition, PlanetId } from "../../game/types";

export const PLANETS: Record<PlanetId, PlanetDefinition> = {
  home: {
    id: "home",
    name: "澄海 I",
    code: "母星",
    color: "#61b2aa",
    environment: "海洋型行星",
    resources: "铁、铜、石、煤、原油、水",
    kind: "terrestrial",
    defaultTemplateId: "oceanic",
    systemId: "helios",
    orbitIndex: 1,
    solarMultiplier: 1,
  },
  ashen: {
    id: "ashen",
    name: "烬原 II",
    code: "熔岩星",
    color: "#d8794d",
    environment: "熔岩型行星",
    resources: "钛、硅、铁、铜、石、煤、硫酸、金伯利矿、分形硅、有机晶体",
    kind: "terrestrial",
    defaultTemplateId: "lava",
    systemId: "helios",
    orbitIndex: 2,
    solarMultiplier: 1.5,
  },
  giant: {
    id: "giant",
    name: "苍岚 III",
    code: "气态巨星",
    color: "#75a9bd",
    environment: "冰气态巨星",
    resources: "氢、氘、可燃冰",
    kind: "gas-giant",
    defaultTemplateId: "ice_giant",
    systemId: "helios",
    orbitIndex: 3,
    solarMultiplier: 0,
    orbitalYields: { hydrogen: 1, deuterium: 0.2, fire_ice: 0.5 },
  },
  frost: {
    id: "frost",
    name: "霜原 I",
    code: "冰原星",
    color: "#91b8c4",
    environment: "永冻冰原行星",
    resources: "铁、铜、钛、硅、可燃冰、光栅石、刺笋结晶",
    kind: "terrestrial",
    defaultTemplateId: "ice_field",
    systemId: "borealis",
    orbitIndex: 1,
    solarMultiplier: 0.8,
  },
  boreal_giant: {
    id: "boreal_giant",
    name: "青冥 II",
    code: "冰巨星",
    color: "#6b94ad",
    environment: "富可燃冰气态巨星",
    resources: "氢、氘、高丰度可燃冰",
    kind: "gas-giant",
    defaultTemplateId: "fire_ice_giant",
    systemId: "borealis",
    orbitIndex: 2,
    solarMultiplier: 0,
    orbitalYields: { hydrogen: 0.8, deuterium: 0.12, fire_ice: 1 },
  },
  magnetar: {
    id: "magnetar",
    name: "极夜 I",
    code: "磁暴星",
    color: "#a48ac2",
    environment: "中子星潮汐锁定行星",
    resources: "铁、铜、钛、硅、单极磁石",
    kind: "terrestrial",
    defaultTemplateId: "tidal_locked",
    systemId: "neutron",
    orbitIndex: 1,
    solarMultiplier: 0.45,
  },
  verdant: {
    id: "verdant", name: "翠环 I", code: "绿洲星", color: "#72aa78", environment: "草原与浅海行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "prairie", systemId: "aurora", orbitIndex: 1, solarMultiplier: 1.2,
  },
  pelagic: {
    id: "pelagic", name: "澜渊 II", code: "深海星", color: "#4d9fb4", environment: "深海群岛行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "mediterranean", systemId: "aurora", orbitIndex: 2, solarMultiplier: 1.05,
  },
  aurora_giant: {
    id: "aurora_giant", name: "天穹 III", code: "氢巨星", color: "#8fa9cf", environment: "高氢气态巨星",
    resources: "氢、氘", kind: "gas-giant", defaultTemplateId: "hydrogen_giant", systemId: "aurora", orbitIndex: 3, solarMultiplier: 0,
    orbitalYields: { hydrogen: 1.35, deuterium: 0.28 },
  },
  dune: {
    id: "dune", name: "赤砂 I", code: "荒漠星", color: "#c7965d", environment: "干旱沙漠行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "desert", systemId: "ember", orbitIndex: 1, solarMultiplier: 1.35,
  },
  cinder: {
    id: "cinder", name: "灰烬 II", code: "火山灰星", color: "#a9634f", environment: "火山灰与熔岩行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "volcanic_ash", systemId: "ember", orbitIndex: 2, solarMultiplier: 1.1,
  },
  ember_giant: {
    id: "ember_giant", name: "红飓 III", code: "气态巨星", color: "#b87964", environment: "高温气态巨星",
    resources: "氢、氘", kind: "gas-giant", defaultTemplateId: "gas_giant", systemId: "ember", orbitIndex: 3, solarMultiplier: 0,
    orbitalYields: { hydrogen: 1.1, deuterium: 0.18 },
  },
  crystal: {
    id: "crystal", name: "晶穹 I", code: "晶漠星", color: "#9ac4c6", environment: "硅晶荒漠行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "crystal_desert", systemId: "sirius", orbitIndex: 1, solarMultiplier: 1.55,
  },
  prairie: {
    id: "prairie", name: "牧云 II", code: "草原星", color: "#89aa67", environment: "风暴草原行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "savanna", systemId: "sirius", orbitIndex: 2, solarMultiplier: 1.2,
  },
  sirius_giant: {
    id: "sirius_giant", name: "银冠 III", code: "冰巨星", color: "#7ba8c5", environment: "明亮冰巨星",
    resources: "氢、氘、可燃冰", kind: "gas-giant", defaultTemplateId: "ice_giant", systemId: "sirius", orbitIndex: 3, solarMultiplier: 0,
    orbitalYields: { hydrogen: 0.9, deuterium: 0.2, fire_ice: 0.7 },
  },
  salt: {
    id: "salt", name: "白盐 I", code: "盐湖星", color: "#c5bf9a", environment: "盐湖与干海盆行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "salt_lake", systemId: "white_dwarf", orbitIndex: 1, solarMultiplier: 0.9,
  },
  obsidian: {
    id: "obsidian", name: "黑曜 II", code: "黑曜星", color: "#746b75", environment: "黑曜火山行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "volcanic_ash", systemId: "white_dwarf", orbitIndex: 2, solarMultiplier: 0.65,
  },
  white_giant: {
    id: "white_giant", name: "苍白 III", code: "冰巨星", color: "#a7bfd0", environment: "低温冰巨星",
    resources: "氢、氘、可燃冰", kind: "gas-giant", defaultTemplateId: "fire_ice_giant", systemId: "white_dwarf", orbitIndex: 3, solarMultiplier: 0,
    orbitalYields: { hydrogen: 0.75, deuterium: 0.14, fire_ice: 1.15 },
  },
  tempest: {
    id: "tempest", name: "风暴 I", code: "飓风星", color: "#5f9d91", environment: "高风速海陆行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "savanna", systemId: "blue_giant", orbitIndex: 1, solarMultiplier: 1.7,
  },
  inferno: {
    id: "inferno", name: "炽核 II", code: "熔岩星", color: "#d65f43", environment: "超高热熔岩行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "lava", systemId: "blue_giant", orbitIndex: 2, solarMultiplier: 1.45,
  },
  abyss: {
    id: "abyss", name: "幽冥 III", code: "永夜星", color: "#66778f", environment: "潮汐锁定永夜行星",
    resources: "由星区种子生成", kind: "terrestrial", defaultTemplateId: "tidal_locked", systemId: "blue_giant", orbitIndex: 3, solarMultiplier: 0.75,
  },
  azure_giant: {
    id: "azure_giant", name: "蓝穹 IV", code: "蓝巨星行星", color: "#5e83bd", environment: "高能气态巨星",
    resources: "氢、氘、可燃冰", kind: "gas-giant", defaultTemplateId: "hydrogen_giant", systemId: "blue_giant", orbitIndex: 4, solarMultiplier: 0,
    orbitalYields: { hydrogen: 1.5, deuterium: 0.35, fire_ice: 0.25 },
  },
};

export const PLANET_LIST = Object.values(PLANETS);
