import type { TechId, TechnologyDefinition } from "../../game/types";

export const TECHNOLOGIES: Record<TechId, TechnologyDefinition> = {
  electromagnetic_matrix: {
    id: "electromagnetic_matrix", name: "电磁矩阵", tier: 0, costs: [{ itemId: "electromagnetic_matrix", amount: 3 }], prerequisites: [],
    summary: "建立以电磁矩阵承载研究数据的基础科研体系。",
    unlocks: ["矩阵研究站制造", "蓝色矩阵科研"],
  },
  electromagnetism: {
    id: "electromagnetism", name: "电磁学", tier: 1, costs: [{ itemId: "electromagnetic_matrix", amount: 5 }], prerequisites: ["electromagnetic_matrix"],
    summary: "掌握稳定电磁场与基础风力发电设备的批量制造。",
    unlocks: ["风力涡轮机制造"],
  },
  solar_energy: {
    id: "solar_energy", name: "太阳能收集", tier: 2, costs: [{ itemId: "electromagnetic_matrix", amount: 8 }],
    prerequisites: ["electromagnetism"],
    summary: "将高纯硅光伏阵列接入行星电网，建立无需燃料的日照发电能力。",
    unlocks: ["太阳能板", "行星日照系数"],
  },
  basic_logistics: {
    id: "basic_logistics", name: "基础物流系统", tier: 2, costs: [{ itemId: "electromagnetic_matrix", amount: 8 }], prerequisites: ["electromagnetism"],
    summary: "建立可持续扩建的标准化物料运输线路。",
    unlocks: ["传送带 Mk.I 制造", "小型储物仓", "四向分流器", "电动机"],
  },
  thermal_power: {
    id: "thermal_power", name: "火力发电", tier: 2, costs: [{ itemId: "electromagnetic_matrix", amount: 8 }],
    prerequisites: ["electromagnetism"],
    summary: "把煤与化工燃料转换为可调度电力，为高耗能工业提供稳定能源。",
    unlocks: ["火力发电厂", "多燃料发电", "按需燃烧"],
  },
  high_efficiency_plasma_control: {
    id: "high_efficiency_plasma_control", name: "高效电浆控制", tier: 3, costs: [{ itemId: "electromagnetic_matrix", amount: 12 }],
    prerequisites: ["basic_logistics", "thermal_power"],
    summary: "为原油萃取、等离子精炼与能源矩阵研究建立控制基础。",
    unlocks: ["原油萃取站", "原油精炼厂", "储液罐", "钢材与电浆部件"],
  },
  energy_matrix: {
    id: "energy_matrix", name: "能量矩阵", tier: 4, costs: [{ itemId: "electromagnetic_matrix", amount: 15 }],
    prerequisites: ["high_efficiency_plasma_control"],
    summary: "把氢的能级结构和高能石墨编码为第二种科学矩阵。",
    unlocks: ["高能石墨", "能量矩阵生产", "红色矩阵科研"],
  },
  energy_storage: {
    id: "energy_storage", name: "能量储存", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["energy_matrix", "basic_logistics"],
    summary: "把电网富余能量封装进可运输蓄电器，并通过能量枢纽在行星间调配电力。",
    unlocks: ["蓄电器", "能量枢纽", "满蓄电器", "自动削峰填谷"],
  },
  fractionation: {
    id: "fractionation", name: "流体分馏", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["energy_matrix", "high_efficiency_plasma_control"],
    summary: "让氢在闭环物流中反复通过分馏塔，稳定分离氘并制造便于运输的氢燃料棒。",
    unlocks: ["分馏塔", "氢分馏", "氢燃料棒"],
  },
  geothermal_power: {
    id: "geothermal_power", name: "地热发电", tier: 6,
    costs: [{ itemId: "electromagnetic_matrix", amount: 18 }, { itemId: "energy_matrix", amount: 18 }],
    prerequisites: ["energy_storage", "high_efficiency_plasma_control"],
    summary: "利用熔岩行星的高温地幔建立不受日照影响的稳定基础电源。",
    unlocks: ["地热发电站", "烬原 II 熔岩电力"],
  },
  high_speed_assembling: {
    id: "high_speed_assembling", name: "高速装配工艺", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["energy_matrix"],
    summary: "改进装配设备的定位与驱动机构，让生产节点在原有配方上获得更高吞吐。",
    unlocks: ["制造台 Mk.II", "制造台原地升级"],
  },
  high_speed_logistics: {
    id: "high_speed_logistics", name: "高速物流系统", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["energy_matrix", "basic_logistics"],
    summary: "以电磁涡轮提高运输线路驱动频率，在相同线路数量下提升物流上限。",
    unlocks: ["传送带 Mk.II", "运输线原地升级", "电磁涡轮"],
  },
  mining_speed_1: {
    id: "mining_speed_1", name: "高效采矿 I", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["energy_matrix"],
    summary: "优化采矿机切削轨迹和矿脉覆盖，使全部固体采矿节点持续增产。",
    unlocks: ["固体矿物开采速度 +50%"],
  },
  proliferator_1: {
    id: "proliferator_1", name: "增产剂 Mk.I", tier: 6,
    costs: [{ itemId: "electromagnetic_matrix", amount: 20 }, { itemId: "energy_matrix", amount: 20 }],
    prerequisites: ["energy_matrix", "high_speed_assembling", "high_speed_logistics"],
    summary: "将煤加工为可控喷涂介质，并建立生产节点的内联喷涂模块。",
    unlocks: ["增产剂 Mk.I", "喷涂机", "额外产出与加速模式"],
  },
  xray_cracking: {
    id: "xray_cracking", name: "X 射线裂解", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 10 }, { itemId: "energy_matrix", amount: 10 }],
    prerequisites: ["energy_matrix"],
    summary: "利用高能光子裂解精炼油，重新分配氢与碳材料产出。",
    unlocks: ["X 射线裂解配方", "氢与石墨替代路线"],
  },
  reforming_refine: {
    id: "reforming_refine", name: "重整精炼", tier: 6,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["xray_cracking", "basic_chemical_engineering"],
    summary: "消耗 2 份精炼油、1 份煤和 1 份氢，重整产出 3 份精炼油，每轮额外获得 1 份精炼油。",
    unlocks: ["重整精炼配方", "精炼油循环增产"],
  },
  high_strength_crystal: {
    id: "high_strength_crystal", name: "高强度晶体", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 10 }, { itemId: "energy_matrix", amount: 10 }],
    prerequisites: ["energy_matrix"],
    summary: "建立硅、钛与碳晶体的高温精炼流程，为结构材料提供基础。",
    unlocks: ["高纯硅块", "钛块", "金刚石", "石矿提炼硅石"],
  },
  basic_chemical_engineering: {
    id: "basic_chemical_engineering", name: "基础化工", tier: 5,
    costs: [{ itemId: "electromagnetic_matrix", amount: 10 }, { itemId: "energy_matrix", amount: 10 }],
    prerequisites: ["energy_matrix"],
    summary: "建立水资源输送与高分子反应设备，开始生产塑料。",
    unlocks: ["抽水站", "化工厂", "塑料配方"],
  },
  polymer_chemistry: {
    id: "polymer_chemistry", name: "高分子化工", tier: 6,
    costs: [{ itemId: "electromagnetic_matrix", amount: 15 }, { itemId: "energy_matrix", amount: 15 }],
    prerequisites: ["basic_chemical_engineering", "xray_cracking"],
    summary: "把塑料、精炼油与水重组为稳定的有机晶体。",
    unlocks: ["有机晶体配方"],
  },
  structure_matrix: {
    id: "structure_matrix", name: "结构矩阵", tier: 7,
    costs: [{ itemId: "electromagnetic_matrix", amount: 20 }, { itemId: "energy_matrix", amount: 20 }],
    prerequisites: ["high_strength_crystal", "polymer_chemistry"],
    summary: "以钛晶石和金刚石编码物质结构，建立第三阶段科研矩阵。",
    unlocks: ["钛晶石", "结构矩阵生产", "黄色矩阵科研"],
  },
  material_delivery_logistics: {
    id: "material_delivery_logistics", name: "物资直送物流", tier: 9,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
    ],
    prerequisites: ["structure_matrix", "basic_logistics"],
    summary: "将三路传送带输入直接写入所在行星的物资托盘，减少重复搬运与仓储操作。",
    unlocks: ["物资配送枢纽", "3 个自动匹配输入接口", "物资托盘直送"],
  },
  proliferator_2: {
    id: "proliferator_2", name: "增产剂 Mk.II", tier: 8,
    costs: [{ itemId: "electromagnetic_matrix", amount: 25 }, { itemId: "energy_matrix", amount: 25 }, { itemId: "structure_matrix", amount: 20 }],
    prerequisites: ["structure_matrix", "high_strength_crystal", "proliferator_1"],
    summary: "利用金刚石稳定喷涂颗粒，在更高耗电下提升增产或加速收益。",
    unlocks: ["增产剂 Mk.II", "额外产出 +20%", "生产加速 +50%"],
  },
  titanium_alloy: {
    id: "titanium_alloy", name: "钛合金", tier: 8,
    costs: [{ itemId: "electromagnetic_matrix", amount: 20 }, { itemId: "energy_matrix", amount: 20 }, { itemId: "structure_matrix", amount: 10 }],
    prerequisites: ["structure_matrix"],
    summary: "利用硫酸改善钛与钢材的晶格结构，制造可承受星际航行环境的结构材料。",
    unlocks: ["硫酸合成", "钛合金配方", "熔岩星硫酸海洋开采"],
  },
  processor: {
    id: "processor", name: "处理器", tier: 8,
    costs: [{ itemId: "electromagnetic_matrix", amount: 20 }, { itemId: "energy_matrix", amount: 20 }, { itemId: "structure_matrix", amount: 10 }],
    prerequisites: ["structure_matrix"],
    summary: "以高纯硅制造微晶元件和处理器，为远程物流调度建立计算基础。",
    unlocks: ["微晶元件", "处理器配方"],
  },
  planetary_logistics: {
    id: "planetary_logistics", name: "行星物流系统", tier: 9,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 10 },
      { itemId: "energy_matrix", amount: 10 },
      { itemId: "structure_matrix", amount: 10 },
    ],
    prerequisites: ["structure_matrix", "processor", "high_speed_logistics"],
    summary: "以物流运输机连接同一行星内的供需站，跨越画布完成无线物资调度。",
    unlocks: ["行星物流站", "物流运输机", "同星球无线运输"],
  },
  interstellar_logistics: {
    id: "interstellar_logistics", name: "星际物流系统", tier: 6,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 20 },
      { itemId: "energy_matrix", amount: 20 },
    ],
    prerequisites: ["energy_matrix", "high_speed_logistics"],
    summary: "建立恒星系内导航与运输协议，开放母恒星系后两颗行星并解锁跨行星物流设施。",
    unlocks: ["烬原 II 与苍穹 III", "星际物流站", "物流运输船", "跨行星跳转与运输调度"],
  },
  nanomaterials: {
    id: "nanomaterials", name: "纳米材料", tier: 10,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 20 },
      { itemId: "energy_matrix", amount: 20 },
      { itemId: "structure_matrix", amount: 20 },
    ],
    prerequisites: ["titanium_alloy", "processor"],
    summary: "把碳与硅材料推进到纳米尺度，为高密度信息载体建立材料基础。",
    unlocks: ["石墨烯", "碳纳米管", "晶格硅"],
  },
  rare_resource_utilization: {
    id: "rare_resource_utilization", name: "稀有资源利用", tier: 14,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 35 },
      { itemId: "energy_matrix", amount: 35 },
      { itemId: "structure_matrix", amount: 35 },
      { itemId: "information_matrix", amount: 35 },
    ],
    prerequisites: ["quantum_chip", "interstellar_logistics", "nanomaterials"],
    summary: "识别稀有矿物的天然微观结构，以替代配方显著缩短六条高阶材料生产链。",
    unlocks: ["可燃冰裂解", "金伯利矿提炼", "分形硅晶格化", "光栅石光学配方", "刺笋结晶纳米管", "单极磁石粒子容器"],
  },
  quantum_chemical_engineering: {
    id: "quantum_chemical_engineering", name: "量子化工", tier: 16,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 50 },
      { itemId: "energy_matrix", amount: 50 },
      { itemId: "structure_matrix", amount: 50 },
      { itemId: "information_matrix", amount: 50 },
      { itemId: "gravity_matrix", amount: 50 },
    ],
    prerequisites: ["gravity_matrix", "rare_resource_utilization"],
    summary: "以量子芯片控制高压反应腔，将全部化工配方速度提升到普通化工厂的两倍。",
    unlocks: ["量子化工厂", "化工厂原地升级", "化工速度 2.00×"],
  },
  orbital_collection: {
    id: "orbital_collection", name: "气态行星开采", tier: 11,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 25 },
      { itemId: "energy_matrix", amount: 25 },
      { itemId: "structure_matrix", amount: 25 },
    ],
    prerequisites: ["interstellar_logistics", "nanomaterials"],
    summary: "将采集与星际供应整合到气态巨星轨道，持续获取氢和少量氘。",
    unlocks: ["轨道采集器", "苍岚 III 轨道部署", "氢与氘自动采集"],
  },
  information_matrix: {
    id: "information_matrix", name: "信息矩阵", tier: 11,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
    ],
    prerequisites: ["interstellar_logistics", "nanomaterials"],
    summary: "将粒子宽带与处理器编码为高密度信息模型，建立第四阶段科研矩阵。",
    unlocks: ["粒子宽带", "信息矩阵生产", "紫色矩阵科研"],
  },
  construction_automation: {
    id: "construction_automation", name: "巨构建筑制造", tier: 13,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 100 },
      { itemId: "energy_matrix", amount: 100 },
      { itemId: "structure_matrix", amount: 100 },
      { itemId: "information_matrix", amount: 100 },
    ],
    prerequisites: ["information_matrix", "high_speed_assembling"],
    summary: "建立巨构级建筑制造中心，按玩家设定的施工库存目标自动取料并持续补足。",
    unlocks: ["建筑制造中心", "目标库存 100", "5 秒自动制造周期"],
  },
  proliferator_3: {
    id: "proliferator_3", name: "增产剂 Mk.III", tier: 12,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
    ],
    prerequisites: ["information_matrix", "nanomaterials", "proliferator_2"],
    summary: "以碳纳米管维持高密度喷涂结构，获得最高增产与生产加速效果。",
    unlocks: ["增产剂 Mk.III", "额外产出 +25%", "生产加速 +100%"],
  },
  research_speed_1: {
    id: "research_speed_1", name: "科研速度 I", tier: 12,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 20 },
      { itemId: "energy_matrix", amount: 20 },
      { itemId: "structure_matrix", amount: 20 },
      { itemId: "information_matrix", amount: 20 },
    ],
    prerequisites: ["information_matrix"],
    summary: "以四色矩阵优化科研站的演算管线，提高持续研究吞吐。",
    unlocks: ["矩阵研究速度 +25%"],
  },
  miniature_particle_collider: {
    id: "miniature_particle_collider", name: "微型粒子对撞机", tier: 13,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
    ],
    prerequisites: ["information_matrix"],
    summary: "以强磁场约束高能粒子，实现氘富集并为奇异物质生产建立设备基础。",
    unlocks: ["微型粒子对撞机", "超级磁场环", "氘", "氘核燃料棒", "粒子容器"],
  },
  fusion_power: {
    id: "fusion_power", name: "可控核聚变", tier: 14,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 40 },
      { itemId: "energy_matrix", amount: 40 },
      { itemId: "structure_matrix", amount: 40 },
      { itemId: "information_matrix", amount: 40 },
    ],
    prerequisites: ["miniature_particle_collider", "energy_storage"],
    summary: "以氘核燃料棒维持稳定聚变反应，为中后期工业提供高密度可调度电力。",
    unlocks: ["微型聚变发电站", "15 MW 聚变电力"],
  },
  quantum_chip: {
    id: "quantum_chip", name: "量子芯片", tier: 13,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
    ],
    prerequisites: ["information_matrix", "nanomaterials"],
    summary: "利用卡西米尔晶体和位面过滤器构建高密度量子运算核心。",
    unlocks: ["钛化玻璃", "卡西米尔晶体", "位面过滤器", "量子芯片"],
  },
  plane_smelting: {
    id: "plane_smelting", name: "位面冶金", tier: 14,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
    ],
    prerequisites: ["miniature_particle_collider", "quantum_chip", "titanium_alloy"],
    summary: "利用强磁约束与位面过滤结构重构熔炼腔体，在相同节点规模下实现双倍冶金吞吐。",
    unlocks: ["位面熔炉", "熔炉原地升级", "熔炼速度 2.00×"],
  },
  gravity_matrix: {
    id: "gravity_matrix", name: "引力矩阵", tier: 14,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 40 },
      { itemId: "energy_matrix", amount: 40 },
      { itemId: "structure_matrix", amount: 40 },
      { itemId: "information_matrix", amount: 40 },
    ],
    prerequisites: ["miniature_particle_collider", "quantum_chip"],
    summary: "将奇异物质、引力透镜与量子芯片组合为第五阶段科研矩阵。",
    unlocks: ["奇异物质", "引力透镜", "引力矩阵生产", "绿色矩阵科研"],
  },
  construction_capacity_1: {
    id: "construction_capacity_1", name: "建筑仓储扩容 I", tier: 16,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 150 },
      { itemId: "energy_matrix", amount: 150 },
      { itemId: "structure_matrix", amount: 150 },
      { itemId: "information_matrix", amount: 150 },
      { itemId: "gravity_matrix", amount: 150 },
    ],
    prerequisites: ["construction_automation", "gravity_matrix"],
    summary: "以引力矩阵压缩施工仓储与调度队列，提高自动补货上限和制造速度。",
    unlocks: ["目标库存上限 500", "自动制造周期 2.5 秒"],
  },
  space_warp: {
    id: "space_warp", name: "空间翘曲", tier: 15,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
      { itemId: "gravity_matrix", amount: 30 },
    ],
    prerequisites: ["gravity_matrix", "interstellar_logistics"],
    summary: "以引力透镜折叠航线距离，为跨恒星物流运输船提供曲率航行能力。",
    unlocks: ["空间翘曲器", "星际站翘曲器仓", "跨恒星航线准备"],
  },
  stellar_exploration: {
    id: "stellar_exploration", name: "恒星探索", tier: 16,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 40 },
      { itemId: "energy_matrix", amount: 40 },
      { itemId: "structure_matrix", amount: 40 },
      { itemId: "information_matrix", amount: 40 },
      { itemId: "gravity_matrix", amount: 40 },
    ],
    prerequisites: ["space_warp", "rare_resource_utilization"],
    summary: "校准恒星级导航阵列，消耗勘探补给发现远方恒星系并建立永久航标。",
    unlocks: ["星图", "北冕座勘探", "赫卡忒中子星系勘探"],
  },
  quantum_printing: {
    id: "quantum_printing", name: "量子打印技术", tier: 15,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
      { itemId: "gravity_matrix", amount: 30 },
    ],
    prerequisites: ["gravity_matrix", "high_speed_assembling"],
    summary: "用量子芯片和粒子宽带控制精密装配过程，进一步压缩高阶物品生产周期。",
    unlocks: ["制造台 Mk.III", "装配速度 1.50×"],
  },
  super_magnetic_logistics: {
    id: "super_magnetic_logistics", name: "超级磁场物流", tier: 15,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
      { itemId: "gravity_matrix", amount: 30 },
    ],
    prerequisites: ["gravity_matrix", "high_speed_logistics"],
    summary: "以超级磁场环稳定高速运输线路，使单线路吞吐提升至基础传送带的五倍。",
    unlocks: ["传送带 Mk.III", "单线物流 30/s"],
  },
  research_speed_2: {
    id: "research_speed_2", name: "科研速度 II", tier: 15,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 20 },
      { itemId: "energy_matrix", amount: 20 },
      { itemId: "structure_matrix", amount: 20 },
      { itemId: "information_matrix", amount: 20 },
      { itemId: "gravity_matrix", amount: 20 },
    ],
    prerequisites: ["gravity_matrix", "research_speed_1"],
    summary: "以五色矩阵继续优化科研站演算管线，使研究吞吐累计提升 50%。",
    unlocks: ["矩阵研究速度累计 +50%"],
  },
  dyson_swarm: {
    id: "dyson_swarm", name: "戴森云", tier: 16,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 50 },
      { itemId: "energy_matrix", amount: 50 },
      { itemId: "structure_matrix", amount: 50 },
      { itemId: "information_matrix", amount: 50 },
      { itemId: "gravity_matrix", amount: 50 },
    ],
    prerequisites: ["gravity_matrix"],
    summary: "以电磁轨道弹射器将太阳帆持续送入恒星轨道，建立可扩张但会衰减的戴森云。",
    unlocks: ["光子合并器", "太阳帆", "电磁轨道弹射器", "戴森云发电"],
  },
  ray_receiver: {
    id: "ray_receiver", name: "射线接收站", tier: 17,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 60 },
      { itemId: "energy_matrix", amount: 60 },
      { itemId: "structure_matrix", amount: 60 },
      { itemId: "information_matrix", amount: 60 },
      { itemId: "gravity_matrix", amount: 60 },
    ],
    prerequisites: ["dyson_swarm"],
    summary: "跨行星共享戴森云输出，并在直接发电和临界光子生成之间分配恒星能。",
    unlocks: ["射线接收站", "电力接收模式", "临界光子模式"],
  },
  antimatter: {
    id: "antimatter", name: "质能储存", tier: 18,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 80 },
      { itemId: "energy_matrix", amount: 80 },
      { itemId: "structure_matrix", amount: 80 },
      { itemId: "information_matrix", amount: 80 },
      { itemId: "gravity_matrix", amount: 80 },
    ],
    prerequisites: ["ray_receiver"],
    summary: "在粒子对撞机中拆分临界光子，并将反物质封装为高密度可调度燃料。",
    unlocks: ["质能转换", "湮灭约束球", "反物质燃料棒"],
  },
  artificial_star: {
    id: "artificial_star", name: "人造恒星", tier: 19,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 100 },
      { itemId: "energy_matrix", amount: 100 },
      { itemId: "structure_matrix", amount: 100 },
      { itemId: "information_matrix", amount: 100 },
      { itemId: "gravity_matrix", amount: 100 },
    ],
    prerequisites: ["antimatter", "fusion_power"],
    summary: "在强约束场中持续湮灭反物质燃料，将终局燃料链转化为超高功率电源。",
    unlocks: ["人造恒星", "72 MW 反物质电力"],
  },
  universe_matrix: {
    id: "universe_matrix", name: "宇宙矩阵", tier: 19,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 100 },
      { itemId: "energy_matrix", amount: 100 },
      { itemId: "structure_matrix", amount: 100 },
      { itemId: "information_matrix", amount: 100 },
      { itemId: "gravity_matrix", amount: 100 },
    ],
    prerequisites: ["antimatter"],
    summary: "把五色矩阵的研究数据与反物质统一编码，形成最终阶段的白色科研矩阵。",
    unlocks: ["宇宙矩阵生产", "六色矩阵科研"],
  },
  micro_black_hole_containment: {
    id: "micro_black_hole_containment", name: "微型黑洞约束工程", tier: 20,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 500 },
      { itemId: "energy_matrix", amount: 500 },
      { itemId: "structure_matrix", amount: 500 },
      { itemId: "information_matrix", amount: 500 },
      { itemId: "gravity_matrix", amount: 500 },
      { itemId: "universe_matrix", amount: 500 },
    ],
    prerequisites: ["universe_matrix"],
    summary: "建立可控微型事件视界，以三个独立接口永久处理任意传送带物资。",
    unlocks: ["微型黑洞连接装置"],
  },
  time_warp_engineering: {
    id: "time_warp_engineering", name: "时间扭曲工程", tier: 20,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 1000 },
      { itemId: "energy_matrix", amount: 1000 },
      { itemId: "structure_matrix", amount: 1000 },
      { itemId: "information_matrix", amount: 1000 },
      { itemId: "gravity_matrix", amount: 1000 },
      { itemId: "universe_matrix", amount: 1000 },
    ],
    prerequisites: ["universe_matrix", "artificial_star"],
    summary: "以指数级电力维持全局时间加速，同时保持离线收益和活动时钟使用真实时间。",
    unlocks: ["时间扭曲装置", "5x 及更高实时模拟倍率"],
  },
  construction_capacity_2: {
    id: "construction_capacity_2", name: "建筑仓储扩容 II", tier: 20,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 300 },
      { itemId: "energy_matrix", amount: 300 },
      { itemId: "structure_matrix", amount: 300 },
      { itemId: "information_matrix", amount: 300 },
      { itemId: "gravity_matrix", amount: 300 },
      { itemId: "universe_matrix", amount: 300 },
    ],
    prerequisites: ["construction_capacity_1", "universe_matrix"],
    summary: "使用宇宙矩阵统一建筑制造协议，将库存与制造吞吐提升到终局规模。",
    unlocks: ["目标库存上限 10万", "自动制造周期 1 秒"],
  },
  research_speed_3: {
    id: "research_speed_3", name: "科研速度 III", tier: 20,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
      { itemId: "gravity_matrix", amount: 30 },
      { itemId: "universe_matrix", amount: 30 },
    ],
    prerequisites: ["universe_matrix", "research_speed_2"],
    summary: "以六色矩阵统一科研站演算管线，使研究吞吐累计提升至 75%。",
    unlocks: ["矩阵研究速度累计 +75%"],
  },
  dyson_sphere_program: {
    id: "dyson_sphere_program", name: "戴森球计划", tier: 21,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 100 },
      { itemId: "energy_matrix", amount: 100 },
      { itemId: "structure_matrix", amount: 100 },
      { itemId: "information_matrix", amount: 100 },
      { itemId: "gravity_matrix", amount: 100 },
      { itemId: "universe_matrix", amount: 100 },
    ],
    prerequisites: ["universe_matrix"],
    summary: "以框架材料和戴森球组件建立可永久存在的恒星级能源结构。",
    unlocks: ["框架材料", "戴森球组件", "戴森球结构规划"],
  },
  vertical_launching_silo: {
    id: "vertical_launching_silo", name: "垂直发射井", tier: 22,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 120 },
      { itemId: "energy_matrix", amount: 120 },
      { itemId: "structure_matrix", amount: 120 },
      { itemId: "information_matrix", amount: 120 },
      { itemId: "gravity_matrix", amount: 120 },
      { itemId: "universe_matrix", amount: 120 },
    ],
    prerequisites: ["dyson_sphere_program"],
    summary: "制造小型运载火箭并通过高功率垂直发射井建设戴森球结构节点。",
    unlocks: ["小型运载火箭", "垂直发射井", "永久结构点"],
  },
  dyson_shell: {
    id: "dyson_shell", name: "戴森壳面", tier: 23,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 150 },
      { itemId: "energy_matrix", amount: 150 },
      { itemId: "structure_matrix", amount: 150 },
      { itemId: "information_matrix", amount: 150 },
      { itemId: "gravity_matrix", amount: 150 },
      { itemId: "universe_matrix", amount: 200 },
    ],
    prerequisites: ["vertical_launching_silo"],
    summary: "让戴森球结构自动吸附轨道太阳帆，将临时戴森云转化为永久发电壳面。",
    unlocks: ["太阳帆自动吸附", "永久壳面发电", "结构容量扩张"],
  },
  mining_speed_2: {
    id: "mining_speed_2", name: "高效采矿 II", tier: 10,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 25 },
      { itemId: "energy_matrix", amount: 25 },
      { itemId: "structure_matrix", amount: 25 },
    ],
    prerequisites: ["structure_matrix", "mining_speed_1"],
    summary: "以结构矩阵重算矿脉覆盖与设备间距，使固体采矿吞吐累计提升至基础速度的两倍。",
    unlocks: ["固体矿物开采速度累计 2.00×"],
  },
  mining_speed_3: {
    id: "mining_speed_3", name: "高效采矿 III", tier: 15,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 40 },
      { itemId: "energy_matrix", amount: 40 },
      { itemId: "structure_matrix", amount: 40 },
      { itemId: "information_matrix", amount: 40 },
      { itemId: "gravity_matrix", amount: 40 },
    ],
    prerequisites: ["gravity_matrix", "mining_speed_2"],
    summary: "利用引力场稳定高密度开采阵列，使固体矿物吞吐达到基础速度的三倍。",
    unlocks: ["固体矿物开采速度累计 3.00×"],
  },
  logistics_engine_1: {
    id: "logistics_engine_1", name: "物流运输引擎 I", tier: 10,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 25 },
      { itemId: "energy_matrix", amount: 25 },
      { itemId: "structure_matrix", amount: 25 },
    ],
    prerequisites: ["interstellar_logistics"],
    summary: "升级运输机和运输船推进系统，将全部常规物流航程速度提升 50%。",
    unlocks: ["物流航行速度 1.50×", "行星航程 5.3 秒", "星际航程 20 秒"],
  },
  logistics_engine_2: {
    id: "logistics_engine_2", name: "物流运输引擎 II", tier: 16,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 45 },
      { itemId: "energy_matrix", amount: 45 },
      { itemId: "structure_matrix", amount: 45 },
      { itemId: "information_matrix", amount: 45 },
      { itemId: "gravity_matrix", amount: 45 },
    ],
    prerequisites: ["space_warp", "logistics_engine_1"],
    summary: "把引力透镜导航并入物流推进器，使全部物流航程速度累计提升至两倍。",
    unlocks: ["物流航行速度累计 2.00×", "行星航程 4 秒", "翘曲航程 6 秒"],
  },
  logistics_capacity_1: {
    id: "logistics_capacity_1", name: "物流载荷扩容 I", tier: 11,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 30 },
      { itemId: "energy_matrix", amount: 30 },
      { itemId: "structure_matrix", amount: 30 },
      { itemId: "information_matrix", amount: 30 },
    ],
    prerequisites: ["information_matrix", "interstellar_logistics"],
    summary: "优化货舱结构与装载算法，使每架运输机和每艘运输船的单次载荷提高 50%。",
    unlocks: ["运输机载荷 38", "运输船载荷 150"],
  },
  logistics_capacity_2: {
    id: "logistics_capacity_2", name: "物流载荷扩容 II", tier: 16,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 45 },
      { itemId: "energy_matrix", amount: 45 },
      { itemId: "structure_matrix", amount: 45 },
      { itemId: "information_matrix", amount: 45 },
      { itemId: "gravity_matrix", amount: 45 },
    ],
    prerequisites: ["gravity_matrix", "logistics_capacity_1"],
    summary: "以引力约束稳定满载货舱，使物流载荷累计提升至基础容量的两倍。",
    unlocks: ["运输机载荷 50", "运输船载荷 200"],
  },
  solar_sail_life_1: {
    id: "solar_sail_life_1", name: "太阳帆轨道寿命 I", tier: 17,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 50 },
      { itemId: "energy_matrix", amount: 50 },
      { itemId: "structure_matrix", amount: 50 },
      { itemId: "information_matrix", amount: 50 },
      { itemId: "gravity_matrix", amount: 50 },
    ],
    prerequisites: ["dyson_swarm"],
    summary: "改进太阳帆姿态控制和光压补偿，将单帆在轨寿命从 20 分钟延长到 30 分钟。",
    unlocks: ["太阳帆在轨寿命 30 分钟"],
  },
  solar_sail_life_2: {
    id: "solar_sail_life_2", name: "太阳帆轨道寿命 II", tier: 20,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 70 },
      { itemId: "energy_matrix", amount: 70 },
      { itemId: "structure_matrix", amount: 70 },
      { itemId: "information_matrix", amount: 70 },
      { itemId: "gravity_matrix", amount: 70 },
      { itemId: "universe_matrix", amount: 70 },
    ],
    prerequisites: ["universe_matrix", "solar_sail_life_1"],
    summary: "以宇宙矩阵预测轨道摄动，将太阳帆在轨寿命累计延长到 40 分钟。",
    unlocks: ["太阳帆在轨寿命累计 40 分钟"],
  },
  ray_transmission_1: {
    id: "ray_transmission_1", name: "射线传输效率 I", tier: 18,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 60 },
      { itemId: "energy_matrix", amount: 60 },
      { itemId: "structure_matrix", amount: 60 },
      { itemId: "information_matrix", amount: 60 },
      { itemId: "gravity_matrix", amount: 60 },
    ],
    prerequisites: ["ray_receiver", "solar_sail_life_1"],
    summary: "校准恒星射线相位与接收阵列，使每台射线接收站额定功率提升至 9 MW。",
    unlocks: ["射线接收上限 9 MW/台"],
  },
  ray_transmission_2: {
    id: "ray_transmission_2", name: "射线传输效率 II", tier: 20,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 80 },
      { itemId: "energy_matrix", amount: 80 },
      { itemId: "structure_matrix", amount: 80 },
      { itemId: "information_matrix", amount: 80 },
      { itemId: "gravity_matrix", amount: 80 },
      { itemId: "universe_matrix", amount: 80 },
    ],
    prerequisites: ["universe_matrix", "ray_transmission_1"],
    summary: "用宇宙矩阵统一发射与接收模型，使每台接收站额定功率累计提升至 12 MW。",
    unlocks: ["射线接收上限累计 12 MW/台"],
  },
  dyson_absorption_1: {
    id: "dyson_absorption_1", name: "壳面吸附效率", tier: 24,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 150 },
      { itemId: "energy_matrix", amount: 150 },
      { itemId: "structure_matrix", amount: 150 },
      { itemId: "information_matrix", amount: 150 },
      { itemId: "gravity_matrix", amount: 150 },
      { itemId: "universe_matrix", amount: 200 },
    ],
    prerequisites: ["dyson_shell", "ray_transmission_2"],
    summary: "同步壳面框架与太阳帆姿态控制，使永久结构吸附轨道太阳帆的速度提高一倍。",
    unlocks: ["壳面太阳帆吸附速度 2.00×"],
  },
  orbital_elevator_engineering: {
    id: "orbital_elevator_engineering", name: "轨道升降工程", tier: 24,
    costs: [{ itemId: "universe_matrix", amount: 100_000 }],
    prerequisites: ["universe_matrix", "interstellar_logistics"],
    summary: "以轨道升降结构改造星际物流站，使其可以原地升级为保留传统功能的 Mk.II。",
    unlocks: ["星际物流站 Mk.II", "太空电梯模式切换"],
  },
  orbital_multi_cargo_bus: {
    id: "orbital_multi_cargo_bus", name: "多物质轨道汇流", tier: 25,
    costs: [{ itemId: "universe_matrix", amount: 1_000_000 }],
    prerequisites: ["orbital_elevator_engineering", "universe_matrix"],
    summary: "把五个传统输入汇合为一个通用入口，并为太空电梯开放五路独立输出。",
    unlocks: ["通用输入口", "五路电梯输出口", "恒星系共享仓库"],
  },
  orbital_energy_recovery: {
    id: "orbital_energy_recovery", name: "轨道升降能量回收", tier: 26,
    costs: [{ itemId: "universe_matrix", amount: 10_000_000 }],
    prerequisites: ["orbital_multi_cargo_bus", "dyson_shell"],
    summary: "回收电梯升降过程中的能量，使太空电梯动态物流能耗降低 50%。",
    unlocks: ["太空电梯能耗 -50%", "联合协议前置"],
  },
  system_space_station_engineering: {
    id: "system_space_station_engineering", name: "恒星系空间站工程", tier: 24,
    costs: [{ itemId: "universe_matrix", amount: 1_000_000 }],
    prerequisites: ["universe_matrix", "dyson_sphere_program", "vertical_launching_silo"],
    summary: "解锁每个已探索恒星系独立建设一座联合空间站的施工工地。",
    unlocks: ["空间站建设工地", "空间站施工发射平台"],
  },
  orbital_modular_assembly: {
    id: "orbital_modular_assembly", name: "轨道模块化装配", tier: 25,
    costs: [{ itemId: "universe_matrix", amount: 10_000_000 }],
    prerequisites: ["system_space_station_engineering", "orbital_multi_cargo_bus"],
    summary: "把空间站施工材料需求降至 90%，并让施工平台吞吐翻倍。",
    unlocks: ["空间站 90% 成本", "物流主干模块"],
  },
  autonomous_station_construction: {
    id: "autonomous_station_construction", name: "自律空间站建造", tier: 26,
    costs: [{ itemId: "universe_matrix", amount: 100_000_000 }],
    prerequisites: ["orbital_modular_assembly", "orbital_energy_recovery"],
    summary: "以自律施工机器人把新空间站材料需求降至 80%，并开放能源与星际运输模块。",
    unlocks: ["空间站 80% 成本", "能源核心模块", "星际运输模块"],
  },
  unified_system_logistics_protocol: {
    id: "unified_system_logistics_protocol", name: "恒星系联合物流协议", tier: 27,
    costs: [{ itemId: "universe_matrix", amount: 1_000_000_000 }],
    prerequisites: ["orbital_energy_recovery", "autonomous_station_construction"],
    summary: "将已建空间站接入共享舰队、共享翘曲仓和银河能源池，开启跨恒星系聚合调度。",
    unlocks: ["最多 8 座空间站聚合物流", "共享舰队与翘曲仓", "银河能源池"],
  },
  quantum_logistics_network: {
    id: "quantum_logistics_network", name: "量子物流网络", tier: 24,
    costs: [
      { itemId: "electromagnetic_matrix", amount: 500 },
      { itemId: "energy_matrix", amount: 500 },
      { itemId: "structure_matrix", amount: 500 },
      { itemId: "information_matrix", amount: 500 },
      { itemId: "gravity_matrix", amount: 500 },
      { itemId: "universe_matrix", amount: 1_000 },
    ],
    prerequisites: ["interstellar_logistics", "space_warp", "universe_matrix"],
    summary: "把已升级的星际物流塔接入一份全宇宙共享物资池；供应物资送达时优先直接入池，下载与溢出缓存仍在五秒边界结算。",
    unlocks: ["量子物流塔接入", "全宇宙共享库存", "量子网络全局吞吐"],
  },
};
